export const ActionTypes = {
  GLOBAL_CONNECTION: 'GLOBAL_CONNECTION',
  IS_LOAD_CHORDS: 'IS_LOAD_CHORDS',
  CHORDS_LIST: 'CHORDS_LIST',
  CHORDS_LIST_EMPTY: 'CHORDS_LIST_EMPTY',
  CHORD_SET_KEYWORD: 'CHORD_SET_KEYWORD',
  CHORD_SET_PAGE: 'CHORD_SET_PAGE'
};

export default ActionTypes;
